// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDddTqMaBEi-EjTJJ2uE9mgDF6IFfDPY0',
    appId: '1:149050519458:web:5abd2f69c65d1c5b77ccfb',
    messagingSenderId: '149050519458',
    projectId: 'mataam-app-80855',
    authDomain: 'mataam-app-80855.firebaseapp.com',
    storageBucket: 'mataam-app-80855.appspot.com',
    measurementId: 'G-PC9Z37CY2L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZgLYm5-Vh3Oi9ahr5fuxcbY6boS4oKrE',
    appId: '1:149050519458:android:24f8639b666e28b577ccfb',
    messagingSenderId: '149050519458',
    projectId: 'mataam-app-80855',
    storageBucket: 'mataam-app-80855.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAXUuceWwof3f5ajI0w_dqrmkkMyo6lSQ',
    appId: '1:149050519458:ios:7d025a8a1e2ee24877ccfb',
    messagingSenderId: '149050519458',
    projectId: 'mataam-app-80855',
    storageBucket: 'mataam-app-80855.appspot.com',
    iosClientId: '149050519458-0cn82odpocm3nv22lflstpe9ogbsdqof.apps.googleusercontent.com',
    iosBundleId: 'com.example.mataamApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAXUuceWwof3f5ajI0w_dqrmkkMyo6lSQ',
    appId: '1:149050519458:ios:f87a0ace1106795277ccfb',
    messagingSenderId: '149050519458',
    projectId: 'mataam-app-80855',
    storageBucket: 'mataam-app-80855.appspot.com',
    iosClientId: '149050519458-llu3131vv4n4hv27af06adoihenq4bdp.apps.googleusercontent.com',
    iosBundleId: 'com.example.mataamApp.RunnerTests',
  );
}
